### ISSUE TITLE
Not receiving mail if email address has uppercase characters

### ISSUE THREAD

**Issue by shiling** [uilicious/inboxkitten#10]
Doesn't work:
1. Send a mail to "[HELLOWORLD@inboxkitten.com](mailto:HELLOWORLD@inboxkitten.com)"
2. Check the inbox: [HELLOWORLD@inboxkitten.com](https://inboxkitten.com/inbox/HELLOWORLD/list)
3. There's nothing.

Works:
1. Send a mail to "[helloworld@inboxkitten.com](mailto:helloworld@inboxkitten.com)"
2. Check the inbox: [helloworld@inboxkitten.com](https://inboxkitten.com/inbox/helloworld/list)
3. Mail is there.
4. Check the inbox: [HELLOWORLD@inboxkitten.com](https://inboxkitten.com/inbox/HELLOWORLD/list)
5. Mail is *also* there.

**Comment by codehakase** [comment]
Any updates on this yet? Anyone currently working on it?

**Comment by jmtiong** [comment]
> Any updates on this yet? Anyone currently working on it?

Hi @codehakase, I will be working on it soon :) sorry for the wait!

**Comment by jmtiong** [comment]
Hi @codehakase! The update is implemented :D
