### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by kianrafiee** [uilicious/inboxkitten#15]
1) Password protected web gui. I use this for private use only and it would comprimise my private information in emails.

2) “New Emails to these accounts” notification list on main page to see what aliases have new emails. Pushover/pushbullet api support would be awesome too. I could see browser notifications like Chromes working well for this as well.

3) Customizable template for web gui. It looks great but would like to strip it down on my private implementation.

Bravo for an ingenius implementation of a disposable email system! Do you guys take donations?

**Comment by jmtiong** [comment]
Hi @kianrafiee !

Thank you for the feature requests! 
1. there is no means of password protect the gui. if you want to use privately, I would suggest you deploying your own version of inboxkitten :)

2. Sounds good to have a browser notifications for it

3. No current plans for customisable templates now 

And as of now, we are not taking donations :)
