### ISSUE TITLE
Click to copy email address!

### ISSUE THREAD

**Issue by marataziat** [uilicious/inboxkitten#16]
I think most of the users want to fastly make an inbox and copy and paste the email for registration.

**Comment by marataziat** [comment]
Or this https://github.com/Inndy/vue-clipboard2 :)

**Comment by jmtiong** [comment]
hi @marataziat! sorry for the delayed response T.T I will be implementing that but I was busy! Will update you again!

**Comment by jmtiong** [comment]
@marataziat, it's finally done! https://github.com/uilicious/inboxkitten/pull/24 :D
