### ISSUE TITLE
Not receiving mails on localhost deployment

### ISSUE THREAD

**Issue by darshil5p** [uilicious/inboxkitten#18]
This is the error shown in console when i access the mailbox. 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:8800/api/v1/mail/list?recipient=gg. (Reason: CORS request did not succeed).

It worked like a charm with firebase deployment , i was trying out custom deployment and unable to solve this. I am stuck here. Could anyone help me out?

**Comment by jmtiong** [comment]
Hi @darshil5p! I hope this is still relevant to you, have you configure the `mailgunConfig.js` over at the api project?

**Comment by darshil5p** [comment]
@jmtiong Yes i have it configured it and i can access the api by directly accessing the api url. It's just that i won't be able to fetch on the main server

**Comment by jmtiong** [comment]
@darshil5p when you say you could not fetch on the main server, do you mean
- fetching directly using the mailgun api e.g. using the `https://api.mailgun.net/v3/`?
- or directly using the localhost api to fetch the mails?

Also, from your UI, is your error message similar to this picture? If this is the case, the most likely issue should be the configuration file on your api server
![image](https://user-images.githubusercontent.com/16659123/53716815-2563fa80-3e91-11e9-96f9-fc7d463da9ba.png)

**Comment by darshil5p** [comment]
@jmtiong do you have discord or something? I have configured everything correctly as in the steps.
I've rechecked it twice now.

**Comment by darshil5p** [comment]
Started everything from fresh on VPS and the issue was fixed, maybe i must have wrongly configured something. Thank you !

**Comment by jmtiong** [comment]
@darshil5p oh okay! Glad that it was fixed! :)
