### ISSUE TITLE
Email content cannot be displayed in Chrome 72

### ISSUE THREAD

**Issue by mpc2008cn** [uilicious/inboxkitten#19]
It seems html contents cannot be rendered.It's OK in Chrome 71.

**Comment by jmtiong** [comment]
Hi @mpc2008cn! Thanks for reporting this issue, fixing it now!

**Comment by jmtiong** [comment]
@mpc2008cn, fixed in https://github.com/uilicious/inboxkitten/pull/22, please give it a try again

**Comment by mpc2008cn** [comment]
It works. Thanks!
