### ISSUE TITLE
I dont know, look...

### ISSUE THREAD

**Issue by CruptexDE** [uilicious/inboxkitten#20]
![screenshot 1](https://user-images.githubusercontent.com/47275890/52280793-f4a9a780-295c-11e9-9a0d-86d9efde0edf.png)

**Comment by CruptexDE** [comment]
I tried it with Mozilla Firefox, Edge... nothing works ^^

**Comment by CruptexDE** [comment]
But in Chrome, Android works

**Comment by darshil5p** [comment]
Yeah same issue i guess the developer has stopped working out on this project or maybe he's already busy in developing something new

**Comment by jmtiong** [comment]
Hi @CruptexDE @darshil5p, apologies to such a long response, I have been busy with other development projects.

Thanks for reporting! Fixing it now :)

**Comment by jmtiong** [comment]
@CruptexDE @darshil5p I fixed it in https://github.com/uilicious/inboxkitten/pull/22, you should be able to view the email now
