### ISSUE TITLE
Add inboxkitten link to repo?

### ISSUE THREAD

**Issue by marataziat** [uilicious/inboxkitten#25]

**Comment by jmtiong** [comment]
hi @marataziat ! what do you mean by that?

**Comment by marataziat** [comment]
I meant add here https://github.com/uilicious/inboxkitten website link on the top right.

**Comment by jmtiong** [comment]
Ohhh xD thanks!

Added!! :)

![image](https://user-images.githubusercontent.com/16659123/53611825-d2791180-3c0a-11e9-9a65-c39ae781a3a4.png)
