### ISSUE TITLE
Webpage missing "build" instructions

### ISSUE THREAD

**Issue by neilio** [uilicious/inboxkitten#3]
Just got this installed. Wanted to let you know the instructions for deploying to firebase on the main inboxkitten homepage is missing the "build.sh" command.

**Comment by PicoCreator** [comment]
Thanks for letting us know, that was a mistype on my part - fixed in : https://github.com/uilicious/inboxkitten/commit/8729ecac8f8bf2161155d8db381fc601afbe7056
