### ISSUE TITLE
Migrating to other hosting options (to cut cost)

### ISSUE THREAD

**Issue by PicoCreator** [uilicious/inboxkitten#30]
In the month of feb, the following happened : $143 of ouch

![Screen Shot 2019-03-20 at 9 21 51 PM](https://user-images.githubusercontent.com/17175484/54730721-67957780-4bc5-11e9-909c-451098f49faa.png)

![Screen Shot 2019-03-20 at 9 15 54 PM](https://user-images.githubusercontent.com/17175484/54730734-78de8400-4bc5-11e9-894b-3490d93c6a8e.png)

As such we should consider using this as an opportunity to deploy onto alternative options, with real production workloads

- Cloudflare for API?
- Commonshost for UI?
- Dedicated linodes?

Also because we do not store the email logs itself, cant even tell what was happening in that timeframe (emails should be gone by now)

**Comment by xmarxthespot** [comment]
ouch.  platform agnostic solutions are preferable

**Comment by PicoCreator** [comment]
Docker support is now out =)

https://hub.docker.com/repository/docker/uilicious/inboxkitten

Now we can host this - on any server

**Comment by PicoCreator** [comment]
PS added a request for hosting sponsors
