### ISSUE TITLE
getHtml and getKey api not working

### ISSUE THREAD

**Issue by alfredosalzillo** [uilicious/inboxkitten#31]
Hi i'm trying to use the api but it not working.

I use the api call https://inboxkitten.com/api/v1/mail/list?recipient=random-as-test3 to get the list of email

```json
[{"tags":[],"envelope":{"targets":"random-as-test3@inboxkitten.com","transport":"smtp","sender":"noctisbels@gmail.com"},"storage":{"url":"https://sw.api.mailgun.net/v3/domains/inboxkitten.com/messages/eyJwIjpmYWxzZSwiayI6IjEyMzY2MmU2LTIxYzMtNDU3Zi05NTlmLWY3MjE5MzNhYmI3OCIsInMiOiIyNjBkNjYzZGJjIiwiYyI6ImIifQ==","key":"eyJwIjpmYWxzZSwiayI6IjEyMzY2MmU2LTIxYzMtNDU3Zi05NTlmLWY3MjE5MzNhYmI3OCIsInMiOiIyNjBkNjYzZGJjIiwiYyI6ImIifQ=="},"log-level":"info","id":"LX3db4z3TO6i5P8n8pW1hw","campaigns":[],"method":"smtp","user-variables":{},"flags":{"is-authenticated":false},"recipient-domain":"inboxkitten.com","timestamp":1553683266.031392,"message":{"headers":{"to":"random-as-test3@inboxkitten.com","message-id":"CACiT9tM=1_owUbufdTxZYrkjuWawq=XpvmtBJtKxcsGK6i6Sgw@mail.gmail.com","from":"Alfredo Salzillo <noctisbels@gmail.com>","subject":"Test"},"attachments":[],"recipients":["random-as-test3@inboxkitten.com"],"size":2570},"recipient":"random-as-test3@inboxkitten.com","event":"accepted"}]
```
Then i try using the key **eyJwIjpmYWxzZSwiayI6IjEyMzY2MmU2LTIxYzMtNDU3Zi05NTlmLWY3MjE5MzNhYmI3OCIsInMiOiIyNjBkNjYzZGJjIiwiYyI6ImIifQ==** to get the Html using the endpoint
https://inboxkitten.com/api/v1/mail/getHtml?mailKey=eyJwIjpmYWxzZSwiayI6IjEyMzY2MmU2LTIxYzMtNDU3Zi05NTlmLWY3MjE5MzNhYmI3OCIsInMiOiIyNjBkNjYzZGJjIiwiYyI6ImIifQ==

but i get the followind error

```javascript
{error: 'TypeError: Fetch API cannot load: https://eyJwIjpmYWxzZSwiayI6IjEyMzY2MmU2LTIxYzMtNDU3Zi05NTlmLWY3MjE5MzNhYmI3OCIsInMiOiIyNjBkNjYzZGJjIiwiYyI6ImIifQ==.api.mailgun.net/v3/domains/inboxkitten.com/messages/undefined'}
```
After looking at the code i think the key is wrong, it's missing the first part of the key **sw-** how is the prefix of the mailgun api url.

**Comment by jmtiong** [comment]
Hi @alfredosalzillo ! Thanks for identifying the issue! I will go fix it :D

**Comment by jmtiong** [comment]
please give it a try again :)

**Comment by alfredosalzillo** [comment]
I have tried again, it still not working even with **sw-** prefix.
But i figure it out that the prefix is not always the same and depend on the **url** returned in the **mail/list** api.

For example for:

`[{"tags":[],"envelope":{"targets":"school-rhyme-42@inboxkitten.com","transport":"smtp","sender":"noctisbels@gmail.com"},"storage":{"url":"https://se.api.mailgun.net/v3/domains/inboxkitten.com/messages/eyJwIjpmYWxzZSwiayI6IjY1MTI3YTc2LWI4MmEtNGVkZS1iMDMxLWE4NDhhYjVjMjUxNSIsInMiOiIyYzUzMzkzMjdjIiwiYyI6ImEifQ==","key":"eyJwIjpmYWxzZSwiayI6IjY1MTI3YTc2LWI4MmEtNGVkZS1iMDMxLWE4NDhhYjVjMjUxNSIsInMiOiIyYzUzMzkzMjdjIiwiYyI6ImEifQ=="},"log-level":"info","id":"le8dVr0WRYSIpeYyz5RBAg","campaigns":[],"method":"smtp","user-variables":{},"flags":{"is-authenticated":false},"recipient-domain":"inboxkitten.com","timestamp":1555399439.172461,"message":{"headers":{"to":"school-rhyme-42@inboxkitten.com","message-id":"CACiT9tN23YYzqyXDUdyH1isb92hD2ffHo3wfU8ruX5H1fmoHng@mail.gmail.com","from":"Alfredo Salzillo <noctisbels@gmail.com>","subject":"test"},"attachments":[],"recipients":["school-rhyme-42@inboxkitten.com"],"size":2579},"recipient":"school-rhyme-42@inboxkitten.com","event":"accepted"}]`

to get the html of the mail i have to use the prefix **se-**.

**Comment by jmtiong** [comment]
yes, the prefix is not always the same, it depends on where the mail is, sorry I didn't mention that. When you retrieve the list of email from that particular address, like what you see in the response, the prefix in the url can be `se` or `sw`. And you have to change it accordingly if you are directly using the api endpoint. But on the frontend side, it is handled for you.

**Comment by alfredosalzillo** [comment]
Thanks for the reply, I'll close this in favour of a feature request. I think it will be useful to add a **kittenKey** properties to the mail list items with the correct key.
