### ISSUE TITLE
Email has no content

### ISSUE THREAD

**Issue by mpc2008cn** [uilicious/inboxkitten#35]
The content says 
> The kittens found no messages :(

# Request URL
```
https://inboxkitten.com/api/v1/mail/getKey?mailKey=se-AgEFS4pJObvw0_4-Aw1EhKLEuwbhVy-xZA==
```

# Response
```
{error: 'TypeError: Cannot read property 'split' of undefined'}
```

**Comment by jmtiong** [comment]
Thanks for reporting! I will be working on this bug asap!

**Comment by jmtiong** [comment]
Hi @mpc2008cn, fixed on https://github.com/uilicious/inboxkitten/pull/36.

**Comment by mpc2008cn** [comment]
Cool. I'll try.
