### ISSUE TITLE
[Feature Request] @inboxkitten.com emails marked as malicious for major social media sites

### ISSUE THREAD

**Issue by awaffle1** [uilicious/inboxkitten#38]
So I've been testing with fake-mails on Discord, and when I tried this, it gave me 2FA lockout. Now, unfortunately, I was testing on my main alt so now I'm locked out with that account. Is it possible if we could change the domain name to a few set choices?

Example:
@inboxkitten.com
@kittensinbox.net
@theinboxofkittens.org
@kittensrus.com

**Comment by xmarxthespot** [comment]
Or pony up forty-four cents for your own domain?

**Comment by awaffle1** [comment]
wait what? Oh... I didn't even know those existed

**Comment by PicoCreator** [comment]
If you purchase any domain - and point it to inboxkitten - it will probably work.

Alternatively, purchase a domain and deploy a copy of this server for use =)

Will gladly accept any sponsored domains to point to this.
