### ISSUE TITLE
tears of the cat

### ISSUE THREAD

**Issue by xmarxthespot** [uilicious/inboxkitten#39]
FireBase is owned by the Big Gay Google.  Is that the only deployment option?

I don't want to make kittens cry.

**Comment by PicoCreator** [comment]
Your can deploy to cloudflare worker alternatively =)

Currently working on a docker container build instead - to make it easier to deploy as a single container.

**Comment by PicoCreator** [comment]
@xmarxthespot - docker support is now out at : https://hub.docker.com/repository/docker/uilicious/inboxkitten

Cheers =)
