### ISSUE TITLE
Not seeing email on self-install email page

### ISSUE THREAD

**Issue by neilio** [uilicious/inboxkitten#4]
Not sure what step I'm missing, but I've got mailgun set up correctly and afaik have the API key configured in my self-install of inboxkitten. I'm not seeing emails sent to my domain in the UI, though, but checking in mailgun (after setting up a catchall route) shows that email is getting received by mailgun correctly.

What am I missing?

**Comment by PicoCreator** [comment]
Hmm, are you doing a firebase deploy? Or a localhost deployment.

If its the localhost deployment, you would need to change the configuration of the UI file to point to your localhost API server.

So for the following `ui/config/apiconfig.js`

```
export default {
	apiUrl: 'http://<API-host-and-port>/api/v1/mail',
	domain: '<domain-of-ui-host>'
}
```

And for `api/config/mailgunConfig.js`

```
module.exports = {
	"apiKey" : "<MAILGUN_API_KEY>",
	"emailDomain" : "<MAILGUN_EMAIL_DOMAIN>",
	"corsOrigin" : "http://<domain-and-port-of-ui-host>"
}
```

**Comment by PicoCreator** [comment]
NOTE : Im updating the README.md to better help guide localhost setup

# Developing on localhost / Custom deployment

Instead of running `./config.sh`, you should setup the config files respectively for the deployment.

## Running api

**Configuring : api/config/mailgunConfig.js**

```
module.exports = {
	"apiKey" : "<MAILGUN_API_KEY>",
	"emailDomain" : "<MAILGUN_EMAIL_DOMAIN>",
	"corsOrigin" : "http://localhost:8000"
}
```

+ MAILGUN_API_KEY : Mailgun private api key
+ MAILGUN_EMAIL_DOMAIN : domain for mailgun 
+ UI_HOST : Url to the UI domain. `http://localhost:8000` is the default for the UI `npm run dev`, 

```
	# Assuming that you are on the root directory of Inboxkitten
	$ cd api
	
	# Start the server
	$ npm start
```

Validate your API server is online at `http://localhost:8800/api/v1/mail/list?recipient=hello-world`

You should see an empty array representing an empty inbox.

## Running ui

**ui/config/apiconfig.js**
```
export default {
	apiUrl: 'http://localhost:8800/api/v1/mail',
	domain: '<MAILGUN_EMAIL_DOMAIN>'
}
```

+ apiUrl : Api server to point to, `localhost:8800` is the default for the api server `npm start`
+ MAILGUN_EMAIL_DOMAIN : domain for mailgun 

```
	# Assuming that you are on the root directory of Inboxkitten
	$ cd ui
	
	# If you do not have a http server, you can install one
	$ npm run dev
```

You can now access it on `http://localhost:8000` and enjoy your kitten-ventures.

**Comment by shiling** [comment]
Could this be related to #10 ?

**Comment by neilio** [comment]
This is a firebase install.

**Comment by neilio** [comment]
Is the MAILGUN_EMAIL_DOMAIN setting my TLD or something different?

**Comment by PicoCreator** [comment]
MAILGUN_EMAIL_DOMAIN should be your mailgun domain, or subdomain (if using the mailgun free tier) as shown on mailgun domain UI

![screen shot 2018-09-25 at 11 10 14 pm](https://user-images.githubusercontent.com/17175484/46023894-39544500-c118-11e8-864d-b0226e0d7b34.png)

So for example it should either be `sandbox3d144f37efdb4764922eb91df590939b.mailgun.org` or `inboxkitten.com` and *not* `mailgun.org`

**Comment by neilio** [comment]
Still can't seem to figure out why this isn't working. Anything I can provide that could help figure out where the issue's happening?

**Comment by jmtiong** [comment]
> Still can't seem to figure out why this isn't working. Anything I can provide that could help figure out where the issue's happening?

Hi @neilio! What are your CORS settings?

```
api/config/mailgunConfig.js

module.exports = {
	"apiKey" : "<MAILGUN_API_KEY>",
	"emailDomain" : "<MAILGUN_EMAIL_DOMAIN>",
	"corsOrigin" : "http://localhost:8000" <-- this particular line
}
```

**Comment by neilio** [comment]
//
// API key and valid mailgun domain supported (using sandbox)
//
module.exports = {
        "apiKey" : "key-3uw97ytc7duelvhfmon55-jisfunbm64",
        "emailDomain" : "nbl.bio",
        "corsOrigin" : "https://app.nbl.bio"
}

**Comment by jmtiong** [comment]
Are you able to run it locally?

For API: Configure
```
module.exports = {
"apiKey" : "key-3uw97ytc7duelvhfmon55-jisfunbm64",
"emailDomain" : "nbl.bio",
"corsOrigin" : "http://localhost:8080"
}
```

For your UI: Configure
```
export default {
	apiUrl: 'http://localhost:8800/api/v1/mail',
	domain: 'nbl.bio'
 }
```

In one terminal, go to your api directory, run `npm start`.

In another terminal, go to your ui directory, run `npm run dev`.

Try accessing it and post the network activity of the UI :)

**Comment by neilio** [comment]
Tried this - I don't see any output in either terminal window when I access the app via either port (8000 or 8001). I do see the test emails as accepted and stored on Mailgun but nothing ever appears in the UI.

**Comment by jmtiong** [comment]
when the request is made via the UI, what is the response of the API call? are you able to provide a screenshot of it?

**Comment by neilio** [comment]
I see no output at all in either terminal window - just "your application is running here: http://localhost:8000" and "app running on port. 8800"

**Comment by jmtiong** [comment]
> I see no output at all in either terminal window - just "your application is running here: http://localhost:8000" and "app running on port. 8800"

Hi @neilio! What i meant was when you access "http://localhost:8000" in your chrome browser, are there any output messages from there? I believe it is still due to the CORS that you could not receive the messages.

Also, check the network traffic when the API call is being made, what are the response of the API call?

**Comment by kianrafiee** [comment]
I'm having the same problem. I have it deployed on firebase. Firebase is pointed to my domain. However, inboxkitten does not see any received emails. Mailgun, however, shows they were stored.

**Comment by kianrafiee** [comment]
@jmtiong localhost ui also does not show any emails even though they are visible in mailgun logs.

**Comment by jmtiong** [comment]
Hi @kianrafiee! When you access the localhost ui, can you check through the developer console and check the API call and post the API response?

**Comment by kianrafiee** [comment]
Sure. Can you show me how to do that?

Regards,
Kian Rafiee

**Comment by jmtiong** [comment]
Once in your browser accessing your localhost ui, 

1. if you are using Mac, you can press `command + alt + i` to open up developer tools, if you are Windows, you can press `ctrl + shift + i`. which looks like this

![image](https://user-images.githubusercontent.com/16659123/47660389-d7cd3d80-dbd1-11e8-993e-28b8a7460c16.png)

2. Go to the inbox that contains emails
3. Select the `console` tab if you are not in it, and refresh and page
4. Screenshot the result
5. Select the `network` tab.
6. Refresh the page again
7. Find and select the one in the screenshot
![image](https://user-images.githubusercontent.com/16659123/47661068-4b237f00-dbd3-11e8-9e35-df008ebcce7f.png)


8. Click on the response tab and screenshot the result

**Comment by neilio** [comment]
I get the same 500 error on both.
![screen shot on 2018-10-29 at 12-41-20](https://user-images.githubusercontent.com/1400/47665695-0f0f0080-db78-11e8-9ede-052ac61d10b5.png)
![screen shot on 2018-10-29 at 12-41-07](https://user-images.githubusercontent.com/1400/47665757-3bc31800-db78-11e8-9b02-8f7211edb045.png)

**Comment by kianrafiee** [comment]
![1](https://user-images.githubusercontent.com/30968904/47684818-6f5e6c00-db91-11e8-9b10-6c28afa9622f.PNG)

That's the error in the Response tab.

**Comment by kianrafiee** [comment]
I'm wondering if its not pulling from the right API key even though its inserted correctly in the config json file that is part of the build. Unless their is another file that the API key is stored in that I dont know about and need to check.

**Comment by kianrafiee** [comment]
Maybe this can be of help: https://stackoverflow.com/questions/17690803/node-js-getaddrinfo-enotfound

**Comment by jmtiong** [comment]
@neilio @kianrafiee just to clarify, on your Firebase are you both using the Spark Plan?

From what I understand, you will need to upgrade to Blaze Plan https://stackoverflow.com/questions/42774807/cloud-functions-for-firebase-getaddrinfo-enotfound

The difference between Spark and Blaze plan is that for Blaze Plan, you have to add in a credit card but still you are able to use it for free as long as it does not exceed the limits of the Spark Plan.

**Comment by kianrafiee** [comment]
That was it! Working now :D

Regards,
Kian Rafiee

**Comment by jmtiong** [comment]
@kianrafiee no problem :) glad to help!

@neilio are yours working now?

**Comment by neilio** [comment]
That fixed it for me, too. Thanks!
