### ISSUE TITLE
Gets caught by validator.pizza

### ISSUE THREAD

**Issue by brian6932** [uilicious/inboxkitten#53]
I don't know if this is easy to avoid or not, but I thought that it may be worth reporting, makes the service a lot less usable imo.
![image_27](https://user-images.githubusercontent.com/18603393/136750949-e141121c-e530-40c1-8f39-f87193612102.png)
https://www.validator.pizza/

**Comment by PicoCreator** [comment]
Hi @brian6932 - thanks for informing, i think with the current amount of traffic inboxkitten handles now, it is advised to selfhost with your own alternative domains, if you need to avoid the "disposable email black list"
